### ISSUE TITLE
GameObject that absorbs the environment

### ISSUE THREAD

**Issue by bhatnathan** [kaszim/agi-project-2#7]
There should be a game object (that it placed using the phycon) that absorbs the environment. It should also have some sort of internal value that says if it has absorbed enough environment to create a resource pack for the player.

- [x] Absorbs Environment in radius from position
- [x] Converts environment absorbed into a float that is added to its fueltank
- [ ] When fuel tank is full create a resource pack (the resource pack functionality doesn't need to be implemented yet)

**Comment by schnigle** [comment]
I am currently working on the terrain and have finished implementing functionality which consumes the resources in a given circle (defined by world space center and radius) and returns the resources gained from this action (as a float).
