### ISSUE TITLE
Movable Tank

### ISSUE THREAD

**Issue by bhatnathan** [kaszim/agi-project-2#8]
A tank gameObject that uses the interface and can move accordingly. This movement should be tanklike (two sliders on the screen mean you can control the wheel pairs individually)

- [ ] Movement for each wheelpair individually using the sliders.

**Comment by schnigle** [comment]
A basic GUI for the slider controls has been added on the controller branch.

**Comment by Yaronye** [comment]
Tank rotate-able and driveable (forwards and backwards)
